services:
    php: 
      build: 
        context: .
        dockerfile: Dockerfile
      container_name: php
      ports:
        - "8002:80"
      volumes:
        - .:/var/www/html
      working_dir: /var/www/html
      depends_on:
        - mysql
      tty: true
      stdin_open: true
    mysql:
      image: mysql:8.0
      container_name: mysql
      ports:
      - "3306:3306"
      environment: 
        MYSQL_ROOT_PASSWORD: root 
        MYSQL_DATABASE: laravel
        MYSQL_USER: laravel
        MYSQL_PASSWORD: laravel
      volumes:
        - db_data:/var/lib/mysql
    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      container_name: phpmyadmin
      restart: always
      depends_on:
        - mysql
      ports:
        - "8002:80"
      environment: 
        - PMA_ARBITRARY= 1
volumes:
  db_data: